# Generated by Django 2.0.3 on 2018-03-15 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('countrycode', models.CharField(default='TTD', max_length=3)),
                ('isActive', models.BooleanField(default=False)),
                ('started', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], default='UG', max_length=2)),
            ],
        ),
    ]
